### ISSUE TITLE
Creator has bias and will not accept pull requests their is a flaw in the creator not the code 

### ISSUE THREAD

**Issue by ericspring08** [Asdfghjkllkj1/Asdfghjkllkj1.github.io#2]

**Comment by Asdfghjkllkj1** [comment]
no

**Comment by ericspring08** [comment]
![Screenshot_20220117-190844_Twitter.jpg](https://user-images.githubusercontent.com/69996843/151639739-f82266a9-3722-4a0e-ae30-0d83a98556c6.jpg)

**Comment by ericspring08** [comment]
Issue is still not fixed
